global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-inference'
    static_configs:
      - targets: ['ai-inference:8080']
    metrics_path: '/metrics'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8084']
    metrics_path: '/metrics'

  - job_name: 'collaboration-service'
    static_configs:
      - targets: ['collaboration:8082']
    metrics_path: '/metrics'

  - job_name: 'assets-service'
    static_configs:
      - targets: ['assets:8083']
    metrics_path: '/metrics'

  - job_name: 'model-registry'
    static_configs:
      - targets: ['model-registry:8081']
    metrics_path: '/metrics'
